name: build

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Calibre
        run: |
          sudo apt install -y libopengl0 libegl1
          wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin
          mkdir -p ~/.local/bin
          ln -s /opt/calibre/calibre ~/.local/bin/calibre
          ln -s /opt/calibre/ebook-convert ~/.local/bin/ebook-convert

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.1

      - name: Setup gitbook
        run: |
          npm ci
          npm run setup
      - name: Generate PDF
        run: |
          npm run generate-pdf
          mv book.pdf mostly-adequate-guide-to-functional-programming-spanish-version.pdf
      - name: Generate EPUB
        run: |
          npm run generate-epub
          mv book.epub mostly-adequate-guide-to-functional-programming-spanish-version.epub
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: mostly-adequate-guide-to-functional-programming-spanish-version.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: EPUB
          path: mostly-adequate-guide-to-functional-programming-spanish-version.epub

      - run: echo "ID=$(git describe --tags --always)" >> $GITHUB_OUTPUT
        id: release-id

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-id.outputs.ID }}
          files: |
            mostly-adequate-guide-to-functional-programming-spanish-version.pdf
            mostly-adequate-guide-to-functional-programming-spanish-version.epub
